defmodule Processing.Adapters.Pay2You.Error do
  @moduledoc """
  This module is mapper for Pay2You error codes.
  """
  @error_grouping %{
    "-1" => "Internal_Error__Aquier",
    "1" => "Internal_Error__P2Y",
    "4" => "Amount_Invalid",
    "5" => "CVV_Invalid",
    "6" => "Card_Expired",
    "7" => "PAN_Invalid",
    "8" => "RecipientPAN_Invalid",
    "9" => "PAN_Empty",
    "074" => "Declined__Aquier",
    "100" => "Declined__Emitent",
    "101" => "Card_Expired",
    "103" => "Declined__Emitent",
    "104" => "Declined__Emitent",
    "105" => "Declined__Emitent",
    "107" => "Declined__Emitent",
    "108" => "Declined__Emitent",
    "109" => "Internal_Error__P2Y",
    "110" => "Declined__Emitent",
    "111" => "Declined__Emitent",
    "114" => "Declined__P2Y",
    "116" => "Funds_Insufficient",
    "118" => "Internal_Error__P2Y",
    "119" => "Declined__P2Y",
    "120" => "Internal_Error__P2Y",
    "121" => "Limits_Exceeded__P2Y",
    "122" => "Declined__P2Y",
    "123" => "Limits_Exceeded__P2Y",
    "124" => "Declined__P2Y",
    "125" => "Card_Expired",
    "129" => "CVV_Invalid",
    "130" => "Limits_Exceeded__P2Y",
    "200" => "Card_Invalid",
    "201" => "Card_Expired",
    "202" => "Card_Invalid",
    "203" => "Declined__P2Y",
    "204" => "Declined__P2Y",
    "205" => "Declined__P2Y",
    "207" => "Declined__P2Y",
    "208" => "Declined__P2Y",
    "209" => "Declined__P2Y",
    "210" => "CVV_Invalid",
    "211" => "CVV_Invalid",
    "290" => "Declined__Aquier",
    "291" => "Internal_Error__P2Y",
    "302" => "Internal_Error__P2Y",
    "306" => "Internal_Error__P2Y",
    "401" => "Internal_Error__P2Y",
    "402" => "Internal_Error__P2Y",
    "403" => "Internal_Error__P2Y",
    "404" => "Internal_Error__P2Y",
    "405" => "Internal_Error__P2Y",
    "406" => "Limits_Exceeded__P2Y",
    "407" => "Internal_Error__P2Y",
    "408" => "Internal_Error__P2Y",
    "409" => "Internal_Error__P2Y",
    "410" => "Internal_Error__P2Y",
    "411" => "Declined__Aquier",
    "412" => "Declined__Aquier",
    "413" => "Declined__Aquier",
    "420" => "Limits_Amount_Exceeded__P2Y",
    "421" => "Limits_Amount_Exceeded__P2Y",
    "430" => "Declined__Emitent",
    "431" => "3DS_Failed",
    "432" => "Declined__P2Y",
    "433" => "Limits_Amount_Exceeded__P2Y",
    "434" => "Limits_Crossborder__P2Y",
    "435" => "Declined__P2Y",
    "436" => "Limits_Count_Exceeded__P2Y",
    "437" => "Limits_Amount_Exceeded__P2Y",
    "438" => "Internal_Error__P2Y",
    "439" => "Internal_Error__P2Y",
    "440" => "Internal_Error__P2Y",
    "441" => "Internal_Error__P2Y",
    "450" => "Internal_Error__P2Y",
    "451" => "Internal_Error__P2Y",
    "452" => "Internal_Error__P2Y",
    "500" => "Internal_Error__Aquier",
    "501" => "Internal_Error__P2Y",
    "502" => "Internal_Error__P2Y",
    "503" => "Internal_Error__P2Y",
    "504" => "Internal_Error__P2Y",
    "505" => "Internal_Error__P2Y",
    "506" => "Internal_Error__P2Y",
    "507" => "Internal_Error__P2Y",
    "508" => "Internal_Error__P2Y",
    "509" => "Internal_Error__P2Y",
    "510" => "Internal_Error__P2Y",
    "511" => "Internal_Error__P2Y",
    "512" => "Internal_Error__P2Y",
    "567" => "Declined__Emitent",
    "568" => "Declined__Emitent",
    "571" => "Declined__Emitent",
    "574" => "Card_Invalid",
    "580" => "CVV_Invalid",
    "581" => "CVV_Invalid",
    "601" => "Internal_Error__P2Y",
    "800" => "Internal_Error__P2Y",
    "801" => "Internal_Error__Aquier",
    "803" => "Payment_Duplicate__Aquier",
    "809" => "Internal_Error__Aquier",
    "810" => "Internal_Error__Aquier",
    "811" => "Internal_Error__Aquier",
    "820" => "Internal_Error__Aquier",
    "880" => "Internal_Error__Aquier",
    "881" => "Internal_Error__Aquier",
    "882" => "Internal_Error__Aquier",
    "888" => "Internal_Error__Aquier",
    "897" => "Internal_Error__Aquier",
    "898" => "Internal_Error__Aquier",
    "899" => "Internal_Error__Aquier",
    "901" => "Card_Expired",
    "902" => "Internal_Error__P2Y",
    "903" => "Internal_Error__P2Y",
    "904" => "Internal_Error__P2Y",
    "905" => "Internal_Error__P2Y",
    "906" => "Limits_Crossborder__Aquier",
    "907" => "Limits_Crossborder__Aquier",
    "908" => "Card_Invalid",
    "909" => "Internal_Error__P2Y",
    "910" => "Declined__Emitent",
    "911" => "Internal_Error__P2Y",
    "912" => "Internal_Error__P2Y",
    "913" => "Payment_Duplicate__P2Y",
    "914" => "Internal_Error__P2Y",
    "915" => "Internal_Error__P2Y",
    "940" => "Declined__Emitent",
    "959" => "Internal_Error__Aquier",
    "998" => "Payment_Duplicate__Aquier",
    "1001" => "Internal_Error__P2Y",
    "10050" => "Internal_Error__P2Y",
    "100500" => "Card_Invalid"
  }

  def get_error_group(code) when is_integer(code) do
    code
    |> Integer.to_string()
    |> get_error_group()
  end

  def get_error_group(code) when is_binary(code) do
    Map.get(@error_grouping, code)
  end
end
